# Generated by Django 5.0.6 on 2024-06-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('publish_date', models.DateField()),
                ('genre', models.CharField(choices=[('fiction', 'Fiction'), ('nonfiction', 'Non-Fiction'), ('mystery', 'Mystery'), ('sci-fi', 'Sci-Fi'), ('fantasy', 'Fantasy'), ('biography', 'Biography'), ('self-help', 'Self-Help'), ('history', 'History')], max_length=20)),
            ],
        ),
    ]
