# Generated by Django 5.0.6 on 2024-06-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_options_remove_books_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='created_books',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='email',
            field=models.EmailField(default='@gmail.com', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='genre',
            field=models.CharField(choices=[('history', 'История'), ('mystery', 'Детектив'), ('biography', 'Биография'), ('self-help', 'Саморазвитие'), ('fiction', 'Художественная литература')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='books',
            name='publish_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
