# Generated by Django 5.0.6 on 2024-06-10 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_books_author_books_created_books_books_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('stars', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviews_books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_books', to='books.books')),
            ],
        ),
    ]
