# Generated by Django 5.0.6 on 2024-06-10 21:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_comment_books'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment_books',
            options={'verbose_name': 'Комментарий книг', 'verbose_name_plural': 'Комментарии книги'},
        ),
        migrations.AlterField(
            model_name='comment_books',
            name='stars',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
