# Generated by Django 5.0.6 on 2024-06-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_comment_books_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age_Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='age_books',
            field=models.ManyToManyField(null=True, to='books.age_books'),
        ),
    ]
