# Generated by Django 5.0.6 on 2024-06-10 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_age_books_books_age_books'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='age_books',
            options={'verbose_name': 'Книга по возрастам', 'verbose_name_plural': 'Книги по возрастам'},
        ),
        migrations.RemoveField(
            model_name='age_books',
            name='age',
        ),
    ]
