# Generated by Django 5.0.6 on 2024-06-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_age_books_options_remove_age_books_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='age_books',
            name='types',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
